ManajemenStok/Models/Inventory/AmprahanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ManajemenStok.Models.Inventory
{
    public class AmprahanPRViewModel
    {
        public string NoBukti { get; set; }
        public DateTime Tanggal { get; set; }
        public int Gudang { get; set; }
        public int KelompokPR { get; set; }
        public string Keterangan { get; set; }
        public DateTime TanggalDibutuhkan { get; set; }
        public decimal Total { get; set; }
        public int SupplierID { get; set; }
        public List<AmprahanPRDetailViewModel> Detail { get; set; }
    }
     
    public class AmprahanViewModel
    {
        public string NoBukti { get; set; }
        public DateTime Tanggal { get; set; }
        public string DariSection { get; set; }
        public string Kepada { get; set; }
        public string Keterangan { get; set; }
        public List<AmprahanDetailViewModel> Detail { get; set; }
    }

    public class AmprahanDetailViewModel 
    {
        public int Id { get; set; } 
        public double Qty { get; set; }
    }

    public class AmprahanPRDetailViewModel
    {
        public int Id { get; set; }
        public decimal Harga { get; set; }
        public double Qty { get; set; }
    }
}

ManajemenStok/Controllers/Inventory/AmprahanController.cs
using ManajemenStok.Entities.SIM;
using ManajemenStok.Helper;
using ManajemenStok.Models.Inventory;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;

namespace ManajemenStok.Controllers.Inventory
{
    [Authorize(Roles = "Inventory")]
    public class AmprahanController : Controller
    {
        private string tipepelayanan = "GUDANG";
        private string tipepelayanan2 = "FARMASI";

        #region ===== L I S T

        [HttpGet]
        public ActionResult Index()
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan && 
                Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan2) return HttpNotFound();
            return View();
        }

        [HttpPost]
        public string List(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan && 
                Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan2) return HConvert.Error("Bukan Tipe Pelayanan");
            try
            {
                if (Request.Cookies["Inventory_Section_LokasiId"] == null) throw new Exception("Lokasi Id tidak ditemukan");
                var lokasi = int.Parse(Request.Cookies["Inventory_Section_LokasiId"].Value);
                var section = Request.Cookies["Inventory_Section_Id"].Value;

                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.INV_ListGudangAmprahan.AsQueryable();
                    if (Request.Cookies["Inventory_Section_Group"].Value == "GUDANG")
                        proses = proses.Where(x => x.LokasiTujuan == lokasi);
                    else
                        proses = proses.Where(x => x.SectionAsal == section);
                    foreach (var x in filter)
                    {
                        if (x.Key == "PeriodeStart" && !string.IsNullOrEmpty(x.Value))
                        {
                            var d = DateTime.Parse(x.Value);
                            proses = proses.Where(y => y.Tanggal >= d);
                        }
                        if (x.Key == "PeriodeEnd" && !string.IsNullOrEmpty(x.Value))
                        {
                            var d = DateTime.Parse(x.Value);
                            proses = proses.Where(y => y.Tanggal <= d);
                        }
                    }
                   
                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        NoBukti = m.NoBukti,
                        Tanggal = m.Tanggal.ToString("dd/MM/yyyy"),
                        SectionAsal = m.SectionAsal_SectionName,
                        SectionTujuan = m.SectionTujuan_SectionName,
                        Keterangan = m.Keterangan,
                        BelumMutasi = !m.Batal && !m.Disetujui,
                        SudahMutasi = !m.Batal && m.Disetujui,
                        BatalAmprah = m.Batal
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        #region ===== S E T U P

        [HttpPost]
        public string Save(string _process, AmprahanViewModel model)
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan &&
                Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan2) return HConvert.Error("Bukan Tipe Pelayanan");
            using (var s = new SIMEntities())
            {
                using (var dbContextTransaction = s.Database.BeginTransaction())
                {
                    try
                    {
                        var userid = User.Identity.GetUserId();
                        var nobukti = "";
                        if (_process == "CREATE")
                        {
                            if (model.Detail == null) model.Detail = new List<AmprahanDetailViewModel>();
                            if (model.Detail.Count == 0) throw new Exception("Detail tidak boleh kosong");
                            nobukti = s.INV_InsertGudangAmprahan(
                                model.Tanggal,
                                model.Keterangan,
                                model.DariSection, 
                                model.Kepada,
                                userid
                            ).FirstOrDefault();
                            if (model.DariSection == model.Kepada) throw new Exception("Section Amprah dan Section Tujuan tidak boleh sama. Silahkan cek terlebih dahulu");
                            if (string.IsNullOrEmpty(nobukti)) throw new Exception("Nobukti tidak ditemukan, INV_InsertGudangAmprahan");
                            foreach (var m in model.Detail) {
                                s.INV_InsertGudangAmprahanDetail(nobukti, m.Id, m.Qty);
                            }
                            s.SaveChanges();
                        }
                        else if (_process == "EDIT")
                        {
                            if (model.Detail == null) model.Detail = new List<AmprahanDetailViewModel>();
                            if (model.Detail.Count == 0) throw new Exception("Detail tidak boleh kosong");
                            nobukti = model.NoBukti;
                            s.INV_UpdateGudangAmprahan(
                                model.NoBukti,
                                model.Keterangan
                            );

                            var d = s.INV_ListGudangAmprahanDetail.Where(x => x.NoBukti == model.NoBukti).ToList();
                            foreach (var x in d)
                            {
                                var _d = model.Detail.FirstOrDefault(y => y.Id == x.Barang_ID);
                                //delete
                                if (_d == null) s.INV_DeleteGudangAmprahanDetail(model.NoBukti, x.Barang_ID);
                            }
                            foreach (var x in model.Detail)
                            {
                                var _d = d.FirstOrDefault(y => y.Barang_ID == x.Id);
                                if (_d == null)
                                {
                                    // new
                                    s.INV_InsertGudangAmprahanDetail(model.NoBukti, x.Id, x.Qty);
                                }
                                else
                                {
                                    // edit
                                    s.INV_UpdateGudangAmprahanDetail(model.NoBukti, x.Id, x.Qty);
                                }

                            }
                            s.SaveChanges();
                        }
                        else if (_process == "DELETE")
                        {
                            nobukti = model.NoBukti;
                            s.INV_GD_trAmprahan_BATAL(model.NoBukti);
                            s.SaveChanges();
                        }

                        var userActivity = new UserActivityModel(Request, User.Identity.GetUserId())
                        {
                            Activity = $"Amprahan-{_process}; id:{model.NoBukti};".ToLower()
                        };
                        UserActivity.InsertUserActivity(userActivity);
                        dbContextTransaction.Commit();

                        return JsonConvert.SerializeObject(new { IsSuccess = true, Id = nobukti });
                    }
                    catch (SqlException ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                    catch (Exception ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                }
            }
        }

        [HttpPost]
        public string Detail(string id)
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan && 
                Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan2) return HConvert.Error("Bukan Tipe Pelayanan");
            try
            {
                using (var s = new SIMEntities())
                {
                    var m = s.INV_ListGudangAmprahanHeader.FirstOrDefault(x => x.NoBukti == id);
                    if (m == null) throw new Exception("Data tidak ditemukan");
                    var d = s.INV_ListGudangAmprahanDetail.Where(x => x.NoBukti == m.NoBukti).OrderBy(x => x.Nama_Barang).ToList();
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = new
                        {
                            NoBukti = m.NoBukti,
                            Tanggal = m.Tanggal.ToString("yyyy-MM-dd"),
                            DariSection = m.SectionAsal,
                            Kepada = m.SectionTujuan,
                            Keterangan = m.Keterangan
                        },
                        Detail = d.ConvertAll(x => new {
                            Id = x.Barang_ID,
                            Kode = x.Kode_Barang,
                            Deskripsi = x.Nama_Barang,
                            Konversi = x.Konversi,
                            Kategori = x.Nama_Kategori,
                            Harga = x.Harga,

ManajemenStok/Controllers/ReportController.cs
using ManajemenStok.Helper;
using ManajemenStok.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace ManajemenStok.Controllers
{
    public class ReportController : Controller
    {
        private string serverpath = "~/Reports/";

        public ActionResult Index(string name, string category)
        {
            var hreport = new HReport(Server, serverpath);
            var r = new ReportInventoryViewModel();
            r.Name = name;
            r.Category = category;
            r.Reports = hreport.List(r.Category);
            return View(r);
        }

        public ActionResult ExportPDF(string category, string filename, string param)
        {
            try
            {
                var server = WebConfigurationManager.AppSettings["reportserver"];
                var database = WebConfigurationManager.AppSettings["reportdatabase"];
                var user = WebConfigurationManager.AppSettings["reportuser"];
                var pass = WebConfigurationManager.AppSettings["reportpass"];

                var hreport = new HReport(Server, serverpath);
                var parameters = JsonConvert.DeserializeObject<List<HReportParameter>>(param);
                var stream = hreport.ExportPDF(server, database, user, pass, category, filename, parameters);
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                return File(stream, "application/pdf");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

ManajemenStok/Views/Amprahan/Index.cshtml
@{
    ViewBag.Title = "Amprahan";
    ViewBag.breadcrumb = new List<SelectListItem>()
{
        new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
    };
}
@using ManajemenStok.Helper
@using Microsoft.AspNet.Identity
<form id="formtable">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title"></h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a class="panel-action action-plus" href="javascript:isetup.opensetup('CREATE')"></a></li>
                    <li><a class="panel-action action-filter" href="javascript:itable.openfilter()"></a></li>
                    <li><a class="panel-action action-help" href="javascript:itable.oprnmodalhelp()"></a></li>
                </ul>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <label>Filter</label>
                <input type="text" name="all" data-itable-filter="All" class="form-control" />
            </div>
            <div class="col-md-2">
                <label>Dari Tanggal</label>
                <input type="date" name="periode" data-itable-filter="PeriodeStart" class="form-control" value="@(DateTime.Today.ToString("yyyy-MM-dd"))" />
            </div>
            <div class="col-md-2">
                <label>Sampai Tanggal</label>
                <input type="date" name="sampai" data-itable-filter="PeriodeEnd" class="form-control" value="@(DateTime.Today.ToString("yyyy-MM-dd"))" />
            </div>
            @*<label class="control-label col-md-2">Show</label>*@
            <div class="col-md-1">
                <label>Page</label>
                <select class="form-control itable-pagesize" style="width: auto;" name="show">
                    <option selected>10</option>
                    <option>25</option>
                    <option>50</option>
                    <option>100</option>
                </select>
            </div>
            <div class="col-md-2">
                <button type="submit" style="margin-top : 27px" class="btn-save btn btn-primary"><i class="icon icon-search4"></i>Cari</button>
            </div>
        </div>
        <div class="dataTables_wrapper no-footer" style="display: block;">
            <div class="datatable-header">
                @*<input type="hidden" data-itable-filter="PeriodeStart" value="@(ConfigModel.Develop ? "" : DateTime.Today.ToString("yyyy-MM-dd"))">
                <input type="hidden" data-itable-filter="PeriodeEnd" value="@(ConfigModel.Develop ? "" : DateTime.Today.ToString("yyyy-MM-dd"))">
                <select class="form-control itable-pagesize hide" style="width: auto;">
                    <option selected>10</option>
                    <option>25</option>
                    <option>50</option>
                    <option>100</option>
                </select>*@
            </div>
            <div class="datatable-scroll">
                <table class="table datatable-basic dataTable no-footer table-xxs">
                    <thead>
                        <tr>
                            <th class="sorting" data-itable-sorting="NoBukti" style="width: 180px;">No Bukti<i></i></th>
                            <th class="sorting" data-itable-sorting="Tanggal" style="width: 100px;">Tanggal<i></i></th>
                            <th class="sorting" data-itable-sorting="SectionAsal_SectionName">Section Asal<i></i></th>
                            <th class="sorting" data-itable-sorting="SectionTujuan_SectionName">Section Tujuan<i></i></th>
                            <th class="sorting" data-itable-sorting="Keterangan">Keterangan<i></i></th>
                            <th class="text-center sorting_disabled" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="datatable-footer">
                <div class="dataTables_info itable-info"></div>
                <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
            </div>
        </div>
    </div>
</form>

<div id="modalfilter" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form autocomplete="off" onsubmit="itable.filtersubmit(this,event)">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Filter</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-4">Periode</label>
                            <div class="col-md-8">
                                <input type="date" name="periode" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Sampai</label>
                            <div class="col-md-8">
                                <input type="date" name="sampai" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Show</label>
                            <div class="col-md-8">
                                <select class="form-control" style="width: auto;" name="show">
                                    <option selected>10</option>
                                    <option>25</option>
                                    <option>50</option>
                                    <option>100</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn-save btn btn-primary"><i class="icon icon-check"></i> OK</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="modalhelp" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Info</h4>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td class="text-center alpha-grey">BELUM MUTASI</td>
                                <td class="text-center alpha-primary">SUDAH MUTASI</td>
                                <td class="text-center alpha-danger">BATAL AMPRAH</td>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var itable;
    document.addEventListener("DOMContentLoaded", function (event) {
        itable = new iTable({
            url: '@Url.Action("List")',
            table: document.getElementById('formtable'),
            orderby: 'NoBukti',
            orderbytype: false,
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    var tbody = '';
                    if (r.Data.length === 0)
                        tbody += '<tr><td colspan="6" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>';
                    $.each(r.Data, function (index, value) {
                        var status =
                            value.BatalAmprah ? 'danger' :
                                value.SudahMutasi ? 'primary' :
                                    value.BelumMutasi ? 'grey' : '';

                        tbody += '<tr class="alpha-' + status + '">';

                        // column
                        tbody += '<td>' + value.NoBukti + '</td>';
                        tbody += '<td class="text-center">' + value.Tanggal + '</td>';
                        tbody += '<td>' + value.SectionAsal + '</td>';
                        tbody += '<td>' + value.SectionTujuan + '</td>';
                        tbody += '<td>' + (value.Keterangan || '-') + '</td>';

                        tbody += '<td class="text-center">';
                        tbody += '<ul class="icons-list">';
                        tbody += '<li class="dropdown">';
                        tbody += '<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>';
                        tbody += '<ul class="dropdown-menu dropdown-menu-right">';

                        // action
                        tbody += '<li><a href="javascript:isetup.opensetup(\'VIEW\',{ id : \'' + value.NoBukti + '\'})"><i class="icon-eye"></i> View</a></li>';

                        if (value.BelumMutasi) {
                            //tbody += '<li><a href="javascript:isetuppr.opensetup(\'EDIT\',{ id : \'' + value.NoBukti + '\'})"><i class="icon-cart-add2"></i> Buatkan PR</a></li>';
                            tbody += '<li><a href="javascript:isetup.opensetup(\'EDIT\',{ id : \'' + value.NoBukti + '\'})"><i class="icon-pencil"></i> Edit</a></li>';
                            tbody += '<li><a href="javascript:isetup.opensetup(\'DELETE\',{ id : \'' + value.NoBukti + '\'})"><i class="icon-trash"></i> Delete</a></li>';
                        }

                        tbody += '<li><a target="_blank" href="@Url.Action("ExportPDF", "Report", new { category = "Transaksi", filename= "SIM_Rpt_GD_Amprahan.rpt" })&param=[{\'Name\':\'@@NoAmprahan\',\'ParameterType\':4,\'Value\':\'' + value.NoBukti + '\'}]"><i class="icon-printer"></i> Report</a></li>';

                        tbody += '</ul>';
                        tbody += '</li>';
                        tbody += '</ul>';
                        tbody += '</td>';
                        tbody += '</tr>';
                    });
                    $(t.table).find('tbody').html(tbody);
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else {
                    alert(r.Message);
                }
            }
        });

        itable.refresh();

        itable.openfilter = function () {
            var f = $('#modalfilter form')[0];
            f['periode'].value = $('#formtable [data-itable-filter="PeriodeStart"]')[0].value;
            f['sampai'].value = $('#formtable [data-itable-filter="PeriodeEnd"]')[0].value;
            f['show'].value = $('#formtable .itable-pagesize')[0].value;
            $('#modalfilter').modal();
        }

        itable.filtersubmit = function (t, e) {
            e.preventDefault();
            var f = $('#modalfilter form')[0];
            $('#formtable [data-itable-filter="PeriodeStart"]')[0].value = f['periode'].value;
            $('#formtable [data-itable-filter="PeriodeEnd"]')[0].value = f['sampai'].value;
            $('#formtable .itable-pagesize')[0].value = f['show'].value;
            itable.pageindex = 0;
            itable.refresh();
            $('#modalfilter').modal('hide');
        }

        itable.oprnmodalhelp = () => {
            $('#modalhelp').modal();
        }
    });
</script>
@Html.Partial("Setup")
@Html.Partial("PR")
@Html.Partial("_LookUpBarang")